name: go_author_client
version: 1.0.0+1
publish_to: none
description: admin client
environment:
  sdk: ">=2.19.4"

dependencies:
  cupertino_icons: ^1.0.5
  get: 4.6.5
  google_fonts: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.5
  fl_chart: ^0.65.0
  flutter_svg: ^2.0.5
  dio: ^5.4.1
  validators: ^3.0.0
  json_annotation: ^4.8.0

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
  shared_preferences: ^2.2.1
  bot_toast: ^4.1.3
  common_utils: ^2.1.0
  syncfusion_flutter_datagrid: ^23.1.44
  syncfusion_localizations: ^23.1.44
  intl: ^0.18.1
  file_picker: ^6.1.1
  dropdown_button2: ^2.3.9
  excel: ^4.0.2
  event_bus: ^2.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  json_serializable: ^6.1.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
